name: Build Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build HTML
      run: make html

    - name: Build PDF
      run: make pdf

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: resume
        path: |
          build/resume.html
          build/resume.pdf
        retention-days: 90
